# Generated by Django 4.2.1 on 2023-05-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_abertura', models.DateTimeField()),
                ('descricao_problema', models.CharField(max_length=255)),
                ('timestamp_solucao', models.DateTimeField()),
                ('descricao_solucao', models.CharField(max_length=255)),
                ('id_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.imovel')),
                ('id_oficina_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.oficina')),
                ('id_reclamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='oficina',
            name='id_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.pessoa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='id_locador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.pessoa'),
        ),
    ]
