# Generated by Django 4.2.1 on 2023-05-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='id_solucionador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solucionador', to='ordemservico.pessoa'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='id_reclamante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamante', to='ordemservico.pessoa'),
        ),
    ]
