# Generated by Django 4.2.1 on 2023-05-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_ordemservico_id_solucionador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='administracao',
            new_name='OrdemServico',
        ),
    ]
