# Generated by Django 4.2.1 on 2023-05-23 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_rename_administracao_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_problema',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_solucao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 22, 21, 23, 211085)),
        ),
    ]
