# Generated by Django 4.2.1 on 2023-05-24 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alter_ordemservico_descricao_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 20, 37, 54, 902966)),
        ),
    ]
