# Generated by Django 4.2.1 on 2023-05-24 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_alter_imovel_latitude_alter_imovel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_solucao',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 20, 56, 30, 80996)),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_solucao',
            field=models.DateTimeField(null=True),
        ),
    ]
