# Generated by Django 4.2.1 on 2023-05-25 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_alter_ordemservico_descricao_solucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 21, 0, 4, 306635)),
        ),
    ]
