# Generated by Django 4.2.1 on 2023-05-25 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0010_alter_ordemservico_id_oficina_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 21, 40, 35, 495078)),
        ),
    ]
