# Generated by Django 4.2.1 on 2023-05-27 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0011_alter_ordemservico_timestamp_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='timestamp_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 13, 29, 11, 787399)),
        ),
    ]
